### ISSUE TITLE
Kod4, potrzebna pomoc

### ISSUE THREAD

**Issue by filiptomczak** [filiptomczak/lab_02#3]
@piotrbonus hej, nie wiem jak zabrac sie za kod4, prosze o pomoc

**Comment by piotrbonus** [comment]
ok, zobacze co da sie zrobic

**Comment by piotrbonus** [comment]
@filiptomczak zobacze co da sie zrobic

**Comment by piotrbonus** [comment]
@filiptomczak sprawdz w nowej galezi dodałem kod4.cpp

**Comment by filiptomczak** [comment]
@piotrbonus o to chodzilo, dzieki!
